# Generated by Django 5.1.4 on 2025-01-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_course_class_id_alter_course_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ManyToManyField(blank=True, to='myapp.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course_id',
            field=models.ManyToManyField(blank=True, to='myapp.course'),
        ),
    ]
